In [10]:
import pandas as pd
import numpy as np
from sklearn import linear_model



In [11]:
df = pd.read_csv('C:/Users/hp/Downloads/MISHTANN.BO.csv')
df.head()

Y1     X1
0  2.730  2.730
1  2.865  2.865
2  3.005  3.005
3  3.155  3.155
4  3.310  3.310

In [15]:

model = linear_model.LinearRegression()
model.fit(df[['X1']],df['Y1'])


LinearRegression()

In [17]:
model.predict([[9]])

array([9.00614777])

In [18]:
import pickle

In [21]:
with open('model_pickle','wb') as file:
    pickle.dump(model, file)
with open('model_pickle','rb') as file:
    new = pickle.load(file)

In [24]:
new.predict([[9]])

array([9.00614777])

In [27]:
import joblib


In [28]:
joblib.dump(model, 'model_joblib')
mj = joblib.load('model_joblib')

In [29]:
mj.predict([[9]])

array([9.00614777])