In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [9]:
df = pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [10]:
df['target'] = digits.target
df.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [43]:
x = df.drop('target', axis ='columns')
y = df.target
y.describe()

count    1797.000000
mean        4.490818
std         2.865304
min         0.000000
25%         2.000000
50%         4.000000
75%         7.000000
max         9.000000
Name: target, dtype: float64

In [44]:
len(y)

1797

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size =0.2)

In [52]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 30)
model.fit(x_train, y_train)


RandomForestClassifier(n_estimators=30)

In [53]:
model.score(x_test, y_test)

0.975

In [56]:
from sklearn.datasets import load_iris
iris = load_iris()

In [59]:
df1 = pd.DataFrame(iris.data)
df1

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [60]:
df1['target'] = iris.target

In [61]:
df1

0    1    2    3  target
0    5.1  3.5  1.4  0.2       0
1    4.9  3.0  1.4  0.2       0
2    4.7  3.2  1.3  0.2       0
3    4.6  3.1  1.5  0.2       0
4    5.0  3.6  1.4  0.2       0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3       2
146  6.3  2.5  5.0  1.9       2
147  6.5  3.0  5.2  2.0       2
148  6.2  3.4  5.4  2.3       2
149  5.9  3.0  5.1  1.8       2

[150 rows x 5 columns]

In [64]:
X = df1.drop('target', axis ='columns')
Y = df1.target

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X,Y, test_size =0.2)

In [80]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 20)
model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=20)

In [81]:
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.9333333333333333

In [84]:
# CROSS VAL SCORE

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import matplotlib.pyplot as plt

In [89]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)



0.9722222222222222

In [91]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.4583333333333333

In [93]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9833333333333333

In [96]:
def get_score(model,x_train, x_test, y_train, y_test ):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [100]:
x

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [105]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 5)

scores_logistic =[]
scores_svm =[]
scores_forest=[]

for train, test in folds.split(x,y):
    x_train, x_test, y_train, y_test = digits.data[train], digits.data[test], digits.target[train], digits.target[test]
    
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_forest.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))
    


In [109]:
import numpy as np
np1 =np.array(scores_logistic)
np1.mean()

0.9533333333333334

In [110]:
from sklearn.model_selection import cross_val_score


In [112]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [123]:
dir(cross_val_score)
#defaults(cross_val_score)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__wrapped__']

In [126]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [135]:
model.fit(X_train, Y_train)

GaussianNB()

In [136]:
model.score(X_test, Y_test)

0.9

In [137]:
data =pd.DataFrame(model.predict_proba(X_test))

In [138]:
data

0             1             2
0    9.308068e-85  9.997778e-01  2.221716e-04
1   2.501581e-181  1.545149e-04  9.998455e-01
2    1.626271e-70  9.999430e-01  5.702147e-05
3    1.000000e+00  9.689135e-21  1.165861e-24
4    1.077891e-33  9.999973e-01  2.720891e-06
5    2.964579e-44  9.999963e-01  3.727377e-06
6   2.376233e-105  9.874942e-01  1.250578e-02
7   1.431487e-105  9.864894e-01  1.351062e-02
8    5.292489e-88  9.988500e-01  1.150008e-03
9    1.000000e+00  2.092636e-18  5.605987e-22
10  3.686428e-148  7.562269e-02  9.243773e-01
11  1.077459e-128  4.067772e-01  5.932228e-01
12  2.445645e-179  5.673730e-04  9.994326e-01
13   3.316939e-76  9.997708e-01  2.291970e-04
14   1.000000e+00  3.202970e-12  8.583734e-17
15   2.162436e-82  9.997238e-01  2.761783e-04
16   1.000000e+00  1.127421e-17  5.261603e-22
17   1.000000e+00  3.233747e-20  3.648575e-24
18  7.439464e-110  9.818898e-01  1.811021e-02
19  3.408946e-109  9.917015e-01  8.298543e-03
20  3.112092e-141  4.102704e-01  5.897296e-01
21  4.794236e-180  5.346569e-04  9.994653e-01
22  7.731822e-141  1.120212e-01  8.879788e-01
23  9.027405e-204  1.616344e-06  9.999984e-01
24   7.463129e-37  9.999982e-01  1.799200e-06
25   2.171413e-94  9.987008e-01  1.299188e-03
26  9.076446e-118  8.895051e-01  1.104949e-01
27  3.852915e-277  3.787084e-12  1.000000e+00
28   1.000000e+00  3.065718e-20  4.902701e-24
29   1.932526e-75  9.999311e-01  6.889077e-05

In [139]:
import pandas as pd

In [142]:
bay =pd.read_csv('C:/Users/hp/OneDrive/Documents/Book1.csv')
bay

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will � b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [149]:
bay['spam']= bay['Category'].apply(lambda x: 1 if x== 'spam' else 0 )

In [150]:
bay

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will � b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [153]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(bay.Message,bay.spam)

In [168]:
from sklearn.feature_extraction.text import CountVectorizer
model= CountVectorizer()

count =model.fit_transform(X_train.values)

In [169]:
count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [170]:
from sklearn.naive_bayes import MultinomialNB
model1 = MultinomialNB()
model1.fit(count,y_train)

MultinomialNB()

In [174]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = model.transform(emails)
model1.predict(emails_count)

array([0, 1], dtype=int64)

In [175]:
model1.predict(count)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [181]:
len(model1.predict(count))

4179

In [184]:
x_test_count = model.transform(X_test)

In [185]:
model1.score(x_test_count,y_test)

0.9892318736539842

In [186]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [189]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [190]:
clf.score(X_test,y_test)

0.9892318736539842